# Generated by Django 3.1.3 on 2020-11-24 16:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Webapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodDonationModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_fd', models.CharField(max_length=256)),
                ('phone_fd', models.IntegerField()),
                ('Location_fd', models.TextField()),
                ('Amount_fd', models.IntegerField()),
                ('FoodType_fd', models.CharField(max_length=256)),
                ('Reason_fd', models.CharField(max_length=256)),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
