# Generated by Django 3.0.5 on 2020-11-30 09:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Webapp', '0003_auto_20201125_1941'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodRequestModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_req', models.CharField(max_length=256)),
                ('phone_req', models.IntegerField()),
                ('Location_req', models.TextField()),
                ('persons_req', models.IntegerField()),
                ('user_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
