# Generated by Django 3.1.2 on 2020-11-02 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Webapp', '0010_auto_20201101_1654'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaqsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=512)),
                ('answer', models.TextField()),
            ],
        ),
    ]
