# Generated by Django 3.1.2 on 2020-11-02 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Webapp', '0011_faqsmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='faqsmodel',
            name='tag',
            field=models.CharField(default='One', max_length=128),
        ),
    ]
