# Generated by Django 3.1.2 on 2020-11-23 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Webapp', '0012_faqsmodel_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='loginUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
            ],
        ),
    ]
