# Generated by Django 3.1.2 on 2020-11-23 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Webapp', '0013_loginuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='loginUser',
        ),
    ]
